### ISSUE TITLE
Umbrella List of Test Issues and Test Cases

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1206]
This is a list of everything that I groomed that may be impacted by https://github.com/kubernetes/kops/pull/1183 <- major API overhaul.  We I would love for folks to take on each one, and aggressively test.  Checkmarks denote that issue is closed, PR is updated, or Test Case is completed.

### PRs

Update the PRs for a rebase

- [x] Add support for extensible IAM permissions #1170
- [x] Add KubeletPreferredAddressTypes #1083 
- [x] Do not check DNS when Topology is Private #1063
- [x] Rolling updates with drain and validate #1134

Note on #1134  I will need to refactor.

### New Issues

- [ ] Can't create cluster using existing subnet https://github.com/kubernetes/kops/issues/1220
- [ ] CNI option does not work on 1.5 https://github.com/kubernetes/kops/issues/856

### Issues

Please test!

- [ ] Kops ignores master instance group min/max size #1168
- [ ] Specifying subnet-ids when creating a new cluster with private topology breaks install #1147
- [x] Kops update with private networking is trying to change NatGateway #1073
- [ ] Refactor bastion to use an instance group approach #1039
- [ ] Backport the backport #1002
- [ ] Private topology: cluster sometimes fails to come up with weave, and cni #945
- [ ] Update docker version or make it configurable #849
- [ ] Bastion improvements #836
- [x] Cleanup cloudup _master_* tags #835
- [ ] Lack of Internet Gateway is Fatal Error on Existing Private VPC #780
- [x] Updating subproperties after cluster creation is prohibited by kops cli #746
- [x] Revisit kops models #744
- [ ] Should validate for duplicated zone at API level #606
- [ ] Prevent any cross-version schema issues #345
- [x] name collision in the terraform output #289
- [x] network-cidr is easily confused with subnet-cidr #45
- [ ] Error after running in --dryrun mode in existing VPC #16

### Test Cases - Create, Edit, Update, Rolling Update, Delete

Please choose one or more and test!

- [ ] One master public networking
- [ ] HA masters public networking
- [ ] One master private networking weave
- [ ] HA masters public networking weave

Note on #1134 - I need to run though most of these, but I would still appreciate the help!

**Comment by chrislovecnm** [comment]
cc: @scottmwebber

**Comment by justinsb** [comment]
@chrislovecnm this feels like a manually curated copy of the information in github issues?  OK to close?

**Comment by chrislovecnm** [comment]
Closing
