### ISSUE TITLE
Ubuntu 2204 tracker

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kops#14140]
Various things we need to cross of before defaulting to 2204

* [ ] Cilium tests are failing
* [ ] https://github.com/kubernetes/kops/issues/14139
* [ ] Are things ready for cgroupv2?

**Comment by zetaab** [comment]
cgroupv2 is worth of mentioning in release notes at least

**Comment by hakman** [comment]
With k8s 1.25, support for cgroups v2 [graduates to stable](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/#support-for-cgroups-v2-graduates-to-stable).

**Comment by olemarkus** [comment]
Was lucky enough to catch one of the weekly cilium u2204 tests passing this night:
https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-grid-cilium-etcd-u2204-k22-docker

**Comment by danports** [comment]
Last open issue in the checklist here was closed (well, rotted away) - perhaps I'll give 22.04 a try and open issues if I run into any problems with it. Are there any other known issues not already noted here?

**Comment by danports** [comment]
FWIW, I haven't had any issues running on 22.04 in the last two weeks, though I haven't tested the specific scenarios that were raised in issues here, like dind.

**Comment by hakman** [comment]
@danports Ubuntu 22.04 will be the default in kOps 1.27.

**Comment by danports** [comment]
I've been running Ubuntu 22.04 with every version of kOps since 1.26.3. kOps 1.23 is over a year old now, so I'd recommend upgrading to the latest version if possible and seeing if the issue still persists.
