### ISSUE TITLE
kops-server: tracking issue

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2959]
Plan for kops-server:

- [ ] Create apiserver with kops API objects
- [ ] Create controllers for kops controllers
- [ ] Revisit UX so that kops-server works well with kubectl (possibly with extensions), and isn't too inconsistent with `kops` CLI tool
- [ ] update godocs in server code
- [ ] unit tests
- [ ] container build (probably bazel)
- [ ] have kops install kops-server addon?
- [ ] documentation
- [ ] add openapi configuration - see https://github.com/kubernetes/kops/issues/2930
