### ISSUE TITLE
[Helped]so many TODO in kops/tests/ , can we solve some of them?

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/kops#8702]
ref:https://github.com/kubernetes/kops/issues/8238

If the following TODO does not exist, I hope you can reply this TODO in here, so I can update this list in time. Or you have solved one of the TODOs and hope you can associate this issue for easy tracking.

Here are TODO under /tests folder.

- [x] tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/additional_cidr/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/containerd-cloudformation/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/externallb/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/mixed_instances/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data:  # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_master-us-west-2a.masters.k8s-iam.us-west-2.td.priv_user_data:  # TODO: Remove?
- [x] tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data:  # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/existing_iam_cloudformation/data/aws_launch_configuration_nodes.k8s-iam.us-west-2.td.priv_user_data:  # TODO: Remove?
- [x] tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml:    # TODO: Remove?
- [x] tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml:    # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
- [ ] tests/integration/update_cluster/existing_iam_cloudformation/cloudformation.json.extracted.yaml:    # TODO: Remove?

**Comment by rifelpet** [comment]
for what its worth, all of these TODO comments are generated from this file: https://github.com/kubernetes/kops/blob/faf57d67b3c30dca8b230f71cf00061bf2c488d4/pkg/model/resources/nodeup.go#L123 so we really only need to address the TODOs there and then updated the expected test outputs
