### ISSUE TITLE
[Helped] so many TODO in kops/cmd  /cloudmock  /util /protokube,can we solve some of them?

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/kops#8703]
ref:https://github.com/kubernetes/kops/issues/8238

Here are TODO under /cmd  /cloudmock /util /protokube   folders.

If the following TODO does not exist, I hope you can reply this TODO in here, so I can update this list in time. Or you have solved one of the TODOs and hope you can associate this issue for easy tracking.

- [ ] cmd/kops/upgrade_cluster.go:	// TODO: What if a kubernetes version is bad?
- [ ] cmd/kops/upgrade_cluster.go:		// TODO: make this less hard coded
- [ ] cmd/kops/upgrade_cluster.go:		// TODO: make less hard-coded
- [ ] cmd/kops/upgrade_cluster.go:		// TODO: Allow --force option to force even if not needed?
- [ ] cmd/kops/upgrade_cluster.go:	// TODO: automate this step
- [ ] cmd/kops/toolbox_convert_imported.go:	// TODO: Switch to cloudup.BuildCloud
- [ ] cmd/kops/edit_cluster.go:	// TODO: if any files we read have > 64KB lines, we'll need to switch to bytes.ReadLine
- [ ] cmd/kops/edit_cluster.go:	// TODO: probably going to be secrets
- [ ] cmd/kops/create.go:		// TODO: this does not support a JSON array
- [ ] cmd/kops/rollingupdatecluster.go:		// TODO should we expose this to the UI?
- [ ] cmd/kops/create_secret_tls.go://	// TODO: Prompt before replacing?
- [ ] cmd/kops/create_secret_tls.go://	// TODO: Keep history?
- [ ] cmd/kops/create_secret_tls.go://		//// TODO: Create a rotate command which keeps the same values?
- [ ] cmd/kops/create_secret_tls.go://		//// TODO: Create a CreateKeypair class, move to fi (this is duplicated code)
- [ ] cmd/kops/create_secret_tls.go://		//	// TODO: Allow resigning of the existing private key?
- [ ] cmd/kops/describe_secrets.go:	// TODO: what is an example??
- [ ] cmd/kops/update_cluster.go:			// TODO: Different message if no changes were needed
- [ ] cmd/kops/update_cluster.go:			// TODO: Detect if rolling-update is needed
- [ ] cmd/kops/create_cluster.go:	// TODO: Can we deprecate this flag - it is awkward?
- [ ] cmd/kops/create_cluster.go:	// TODO: Reuse rootCommand stateStore logic?
- [ ] cmd/kops/create_cluster.go:	// TODO: This is the same code as in defaults - try to dedup?
- [ ] cmd/kops/create_cluster.go:		// TODO: Maybe just embed UpdateClusterOptions in CreateClusterOptions?
- [ ] cmd/kops/toolbox_dump.go:	// TODO: Push up to top-level command?
- [ ] cmd/kops/delete_secret.go:		// TODO: it would be friendly to print the matching keys
- [ ] cmd/kops/integration_test.go:	// TODO fix tf for phase, and allow override on validation
- [ ] cmd/kops/validate_cluster.go:	// TODO: Refactor into util.Factory
- [ ] cmd/kops/delete_instancegroup.go:	// TODO make this drain and validate the ig?
- [ ] cmd/kops/delete_instancegroup.go:	// TODO implement drain and validate logic
- [ ] cmd/kops/create_ig.go:	// TODO: Create Enum helper - or is there one in k8s already?
- [ ] cmd/kops-controller/controllers/node_controller.go:	// TODO: Should we be paranoid?
- [ ] cloudmock/aws/mockautoscaling/group.go:					Activity: nil, // TODO
- [ ] cloudmock/aws/mockiam/iamrolepolicy.go:			// TODO: check regex?
- [ ] cloudmock/aws/mockiam/iamrolepolicy.go:			// TODO: check regex?
- [ ] cloudmock/aws/mockiam/iamrolepolicy.go:			// TODO: check regex?
- [ ] cloudmock/aws/mockiam/iamrolepolicy.go:			// TODO: check regex?
- [ ] cloudmock/aws/mockiam/iaminstanceprofile.go:	// TODO: Some fields
- [ ] cloudmock/aws/mockec2/volumes.go:	// TODO: a few fields
- [ ] cloudmock/aws/mockec2/securitygroups.go:	// TODO: We need to fold permissions
- [ ] cloudmock/aws/mockec2/securitygroups.go:	// TODO: We need to fold permissions
- [ ] cloudmock/aws/mockec2/subnets.go:	// TODO: More fields
- [ ] cloudmock/aws/mockec2/subnets.go:	// TODO: We need to fold permissions
- [ ] cloudmock/aws/mockroute53/zones.go:		// TODO: Use correct error
- [ ] cloudmock/aws/mockroute53/zones.go:		// TODO: Use correct error
- [ ] cloudmock/aws/mockroute53/records.go:		// TODO: Use correct error
- [ ] cloudmock/aws/mockroute53/records.go:		// TODO: Use correct error
- [ ] cloudmock/aws/mockroute53/records.go:		// TODO: Use correct error
- [ ] cloudmock/aws/mockroute53/records.go:		// TODO: Use correct error
- [ ] cloudmock/aws/mockroute53/records.go:				// TODO: Use correct error
- [ ] cloudmock/aws/mockroute53/records.go:				// TODO: Use correct error
- [ ] cloudmock/aws/mockroute53/records.go:			// TODO: Use correct error
- [ ] util/pkg/reflectutils/walk.go:			// TODO: I think we are double visiting here; we should instead pass down structField into reflectRecursive
- [ ] util/pkg/reflectutils/walk.go:		// TODO: internal types have panic guards against json.Marshaling to prevent
- [ ] util/pkg/vfs/context.go:	// TODO: Should we fall back to read-only?
- [ ] util/pkg/vfs/s3fs.go:		// TODO: Check for not-exists, return os.NotExist
- [ ] util/pkg/vfs/s3fs.go:// TODO: should we enable versioning?
- [ ] util/pkg/vfs/fs.go:// TODO: should we take a file lock or equivalent here?  Can we use RENAME_NOREPLACE ?
- [ ] util/pkg/vfs/gsfs.go:			// TODO: Check for not-exists, return os.NotExist
- [ ] util/pkg/vfs/gsfs.go:// TODO: should we enable versioning?
- [ ] util/pkg/vfs/swiftfs.go:	// TODO: Unsure if this is the correct section for region
- [ ] util/pkg/vfs/swiftfs.go:// TODO: should we enable versioning?
- [ ] util/pkg/vfs/sshfs.go:		// TODO: Retry if concurrently created?
- [ ] util/pkg/vfs/memfs.go:	// TODO: Copy?
- [ ] util/pkg/vfs/s3context.go:	// TODO: perhaps make region regex more specific, i.e. (us|eu|ap|cn|ca|sa), to prevent matching bucket names that match region format?
- [ ] util/pkg/vfs/ossfs.go:// TODO: should we enable versioning?
- [ ] channels/pkg/cmd/apply_channel.go:		// TODO: Cache lookups to prevent repeated lookups?
- [ ] protokube/pkg/protokube/aws_volume.go:	// TODO: Check for actual devices in use (like cloudprovider does)
- [ ] protokube/pkg/protokube/aws_volume.go:				// TODO: Wait for device to appear?
- [ ] protokube/pkg/protokube/kube_boot_task.go://		// TODO: Support more than one bootstrap task?
- [ ] protokube/pkg/protokube/kube_boot_task.go://		// TODO: Have multiple proto-kubelet configurations to support recovery?
- [ ] protokube/pkg/protokube/kube_boot_task.go://	// TODO: Use a file lock or similar to only start proto-kubelet if real-kubelet is not running?
- [ ] protokube/pkg/protokube/etcd_manifest.go:	// TODO: TLS options
- [ ] protokube/pkg/protokube/etcd_manifest.go:	// TODO: Liveness probe?
- [ ] protokube/pkg/protokube/do_volume.go:// TODO: use tags once it's supported for volumes
- [ ] protokube/pkg/protokube/tainter.go:			// TODO: Should we keep going?
- [ ] protokube/pkg/protokube/volumes.go:	// TODO: Maybe the events cluster can just be a PetSet - do we need it for boot?
- [ ] protokube/pkg/protokube/kube_boot.go:	// TODO: Check/log status of kubelet
- [ ] protokube/pkg/protokube/volume_mounter.go:	// TODO: mount ephemeral volumes (particular on AWS)?
- [ ] protokube/pkg/protokube/volume_mounter.go:	// TODO: can we now use IsLikelyNotMountPoint or IsMountPointMatch instead here
- [ ] protokube/pkg/protokube/ali_volume.go:		// TODO: shall we raise error here?
- [ ] protokube/pkg/protokube/ali_volume.go:	// TODO: what if this volume has already been attached to another instance?
- [ ] protokube/pkg/protokube/ali_volume.go:			// TODO: DeleteWithInstance?
- [ ] protokube/pkg/protokube/ali_volume.go:		// TODO: Do we have to wait for attach to complete?
- [ ] protokube/pkg/protokube/gce_volume.go:	// TODO: Apply filters
- [ ] protokube/pkg/protokube/gce_volume.go:		// TODO: The k8s GCE provider sets Kind, but this seems wrong.  Open an issue?
- [ ] protokube/pkg/protokube/gce_volume.go:	// TODO: Wait for device to appear?
- [ ] protokube/pkg/gossip/gce/seeds.go:	// TODO: Does it suffice to just query one zone (as long as we sort so it is always the first)?
- [ ] protokube/pkg/gossip/gce/seeds.go:			// TODO: Filter by fields (but ask about google issue 29524655)
- [ ] protokube/pkg/gossip/gce/seeds.go:			// TODO: Match clusterid?
- [ ] protokube/pkg/gossip/gce/seeds.go:				// TODO: Expose multiple IPs topologies?
- [ ] protokube/pkg/gossip/gce/seeds.go:					// TODO: Check e.g. Network
- [ ] protokube/pkg/gossip/memberlist/state.go:	// TODO: This relies on NTP.  We could have a g-counter or something, but this is probably good enough for V1
- [ ] protokube/pkg/gossip/memberlist/state.go:		// TODO: Check that now > existing version?
- [ ] protokube/pkg/gossip/memberlist/gossip.go:	// TODO: get port from other config?
- [ ] protokube/pkg/gossip/memberlist/gossip.go:		// TODO: Make it so that only one node polls, or at least statistically get close
- [ ] protokube/pkg/gossip/dns/provider/rrset.go:	// TODO: Check if it is one of the well-known types?
- [ ] protokube/pkg/gossip/dns/provider/zone.go:		// TODO: Check existing?  Probably not...
- [ ] protokube/pkg/gossip/dns/dns.go:		// TODO: We might want to keep old records alive for a bit
- [ ] protokube/pkg/gossip/mesh/state.go:	// TODO: This relies on NTP.  We could have a g-counter or something, but this is probably good enough for V1
- [ ] protokube/pkg/gossip/mesh/state.go:		// TODO: Check that now > existing version?
- [ ] protokube/pkg/gossip/mesh/gossip.go:		// TODO: Include ourselves?  Exclude ourselves?
- [ ] protokube/pkg/gossip/mesh/gossip.go:		// TODO: Make it so that only one node polls, or at least statistically get close
- [ ] protokube/pkg/gossip/ali/seeds.go:		// TODO: pending? starting?
- [ ] protokube/pkg/gossip/ali/seeds.go:		// TODO: Multiple IP addresses?
- [ ] protokube/cmd/protokube/main.go:		// TODO: Maybe only master needs DNS?
- [ ] protokube/cmd/protokube/main.go:		// TODO: sort?
