### ISSUE TITLE
[Helped] so many TODO in kops/dnsprovider , can we solve some of them?

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/kops#8705]
ref:https://github.com/kubernetes/kops/issues/8238

Here are TODO under /dnsprovider  folders.
If the following TODO does not exist, I hope you can reply this TODO in here, so I can update this list in time. Or you have solved one of the TODOs and hope you can associate this issue for easy tracking.

- [ ] dnsprovider/pkg/dnsprovider/rrstype/rrstype.go:	// TODO:  Add other types as required
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/rrchangeset.go:		// TODO: We could maybe tweak this to fetch just the records we care about
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/stubs/clouddns.go:	// TODO: We don't need these yet, so they remain unimplemented.  Add later as required.
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Id() string  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Kind() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// StartTime() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Status() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Context(ctx context.Context) *ChangesCreateCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Fields(s ...googleapi.Field) *ChangesCreateCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Context(ctx context.Context) *ChangesGetCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Fields(s ...googleapi.Field) *ChangesGetCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// IfNoneMatch(entityTag string) *ChangesGetCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Context(ctx context.Context) *ChangesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Fields(s ...googleapi.Field) *ChangesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// IfNoneMatch(entityTag string) *ChangesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// MaxResults(maxResults int64) *ChangesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// PageToken(pageToken string) *ChangesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Pages(ctx context.Context, f func(*ChangesListResponse) error) error // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// SortBy(sortBy string) *ChangesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// SortOrder(sortOrder string) *ChangesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Changes() []*Change // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Kind() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// NextPageToken() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ServerResponse() googleapi.ServerResponse // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ForceSendFields() []string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Create(project string, managedZone string, change *Change) *ChangesCreateCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Get(project string, managedZone string, changeId string) *ChangesGetCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// List(project string, managedZone string) *ChangesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// CreationTime() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Description() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Kind() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// NameServerSet() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// NameServers() []string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ServerResponse() googleapi.ServerResponse // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ForceSendFields() []string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Context(ctx context.Context) *ManagedZonesCreateCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Fields(s ...googleapi.Field) *ManagedZonesCreateCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Context(ctx context.Context) *ManagedZonesDeleteCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Fields(s ...googleapi.Field) *ManagedZonesDeleteCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Context(ctx context.Context) *ManagedZonesGetCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Fields(s ...googleapi.Field) *ManagedZonesGetCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// IfNoneMatch(entityTag string) *ManagedZonesGetCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Context(ctx context.Context) *ManagedZonesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Fields(s ...googleapi.Field) *ManagedZonesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// IfNoneMatch(entityTag string) *ManagedZonesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// MaxResults(maxResults int64) *ManagedZonesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// PageToken(pageToken string) *ManagedZonesListCall // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Pages(ctx context.Context, f func(*ManagedZonesListResponse) error) error // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Kind() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ManagedZones() []*ManagedZone // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// NextPageToken string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ServerResponse() googleapi.ServerResponse // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ForceSendFields() []string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// NewManagedZonesService(s *Service) *ManagedZonesService // TODO: Add to service if needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Id()  string  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Kind() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Number() uint64 // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Quota() *Quota // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ServerResponse()  googleapi.ServerResponse // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ForceSendFields() []string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Kind() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ForceSendFields []string  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Context(ctx context.Context) *ResourceRecordSetsListCall  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Fields(s ...googleapi.Field) *ResourceRecordSetsListCall  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// IfNoneMatch(entityTag string) *ResourceRecordSetsListCall  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// MaxResults(maxResults int64) *ResourceRecordSetsListCall  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// PageToken(pageToken string) *ResourceRecordSetsListCall  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// Kind() string  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// NextPageToken() string  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ServerResponse() googleapi.ServerResponse  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// ForceSendFields() []string  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// NewResourceRecordSetsService(s *Service) *ResourceRecordSetsService // TODO: add to service as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// BasePath() string  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:		// UserAgent() string // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/google/clouddns/internal/interfaces/interfaces.go:	// New(client *http.Client) (*Service, error)  // TODO: Add as needed
- [ ] dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go:	output := route53.ListResourceRecordSetsOutput{} // TODO: Support optional input args.
- [ ] dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go:				return nil, fmt.Errorf("attempt to create duplicate rrset %s", key) // TODO: Return AWS errors with codes etc
- [ ] dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go:				return nil, fmt.Errorf("attempt to delete non-existent rrset %s", key) // TODO: Check other fields too
- [ ] dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go:			// TODO - not used yet
- [ ] dnsprovider/pkg/dnsprovider/providers/aws/route53/stubs/route53api.go:	return output, nil // TODO: We should ideally return status etc, but we don't' use that yet.
- [ ] dnsprovider/pkg/dnsprovider/providers/aws/route53/route53.go:	// Connect to AWS Route53 - TODO: Do more sophisticated auth
- [ ] dnsprovider/pkg/dnsprovider/providers/coredns/rrchangeset.go:			// TODO: I think the semantics of the other providers are different; they operate at the record level, not the individual rrdata level
- [ ] dnsprovider/pkg/dnsprovider/providers/coredns/rrchangeset.go:			// TODO: I think the semantics of the other providers are different; they operate at the record level, not the individual rrdata level
- [ ] dnsprovider/pkg/dnsprovider/providers/coredns/rrchangeset.go:			// TODO: We need to cleanup empty dirs in etcd

/help
