### ISSUE TITLE
[Helped] so many TODO in kops/tools  /docs  /dns-controller /hack  ,can we solve some of them?

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/kops#8706]
ref:https://github.com/kubernetes/kops/issues/8238

Here are TODO under /tools  /docs  /dns-controller /hack folders.

If the following TODO does not exist, I hope you can reply this TODO in here, so I can update this list in time. Or you have solved one of the TODOs and hope you can associate this issue for easy tracking.

- [ ] WORKSPACE:# TODO(fejta): use load.bzl, repos.bzl from repo-infra
- [ ] tools/bazel.rc:# TODO: Remove once we expect everyone is running bazel >= 0.18
- [ ] tools/bazel.rc:build:ci --host_force_python=PY2 # TODO(fejta): noop stub to allow CI to use --config=ci
- [ ] README-ES.md:Tambi茅n alentamos a TODOS los participantes activos de la comunidad a actuar como si fueran
- [ ] images/BUILD.bazel:    # TODO: Replace systemd with direct calls, or chroot into rootfs
- [ ] images/BUILD.bazel:    # TODO: figure out if there's a way to add files
- [ ] images/BUILD.bazel:    tags = ["local"],  # TODO(fejta): make xz toolchain hermetic
- [ ] images/kops-server/Dockerfile:# TODO
- [ ] docs/getting_started/gce.md:TODO: Can we get rid of `gcloud auth application-default login` ?
- [ ] docs/getting_started/gce.md:TODO: Fix bug where zones not showing up
- [ ] docs/getting_started/gce.md:TODO: Fix subnets vs regions
- [ ] docs/getting_started/gce.md:TODO: We don't need this on GCE; remove SSH key requirement
- [ ] docs/vsphere-development-status.md:**TODO** Issues listed below require proper labels to be assigned, especially P0.
- [ ] docs/operations/addons.md:This means that a user can edit a deployed addon, and changes will not be replaced, until a new version of the addon is installed. The long-term direction here is that addons will mostly be configured through a ConfigMap or Secret object, and that the addon manager will (TODO) not replace the ConfigMap.
- [ ] docs/operations/addons.md:to construct a `--prune` argument (TODO), so that objects that existed in the
- [ ] docs/tutorial/working-with-instancegroups.md:TODO enable cluster autoscaler or GCE autoscaler
- [ ] docs/tutorial/working-with-instancegroups.md:TODO link to API reference docs
- [ ] docs/tutorial/working-with-instancegroups.md:TODO can we have a dirty flag somehow
- [ ] docs/tutorial/working-with-instancegroups.md:TODO: Make Changes may require instances to restart: kops rolling-update cluster appear selectively
- [ ] docs/tutorial/working-with-instancegroups.md:TODO: Auto select debian-cloud/debian-9 => debian-cloud/debian-9-stretch-v20170918
- [ ] docs/tutorial/working-with-instancegroups.md:TODO: Clean up rolling-update cluster stdout
- [ ] docs/tutorial/working-with-instancegroups.md:TODO: Pause after showing preview, to give a change to Ctrl-C
- [ ] docs/tutorial/upgrading-kubernetes.md:TODO: Do we drain, validate and then restart
- [ ] docs/tutorial/upgrading-kubernetes.md:TODO: Fix timings in rolling update
- [ ] dns-controller/pkg/watchers/ingress.go:			// TODO: Support ELB aliases
- [ ] dns-controller/pkg/watchers/service.go:					// TODO: Support ELB aliases
- [ ] dns-controller/pkg/watchers/service.go:			// TODO: Emit event so that users are informed of this
- [ ] dns-controller/pkg/dns/dnscontroller.go:					// TODO: Support chains: alias of alias (etc)
- [ ] dns-controller/pkg/dns/dnscontroller.go:		// TODO: Post event into service / pod
- [ ] dns-controller/pkg/dns/dnscontroller.go:	// TODO: work-around before ResourceRecordSets.List() is implemented for CoreDNS
- [ ] dns-controller/pkg/dns/dnscontroller.go:		// TODO: Post event into service / pod
- [ ] dns-controller/pkg/dns/dnscontroller.go:	// TODO: work-around before ResourceRecordSets.List() is implemented for CoreDNS
- [ ] kube-discovery/cmd/kube-discovery/main.go:	// TODO: Combined with previously discovered records (with a sliding window?)
- [ ] kube-discovery/cmd/kube-discovery/main.go:	// TODO: Support an iptables / ipvs backend?
- [ ] kube-discovery/cmd/kube-discovery/main.go:	// TODO: Verify resolved records against certificates?
- [ ] kube-discovery/cmd/kube-discovery/main.go:			// TODO: Ignore if port is not 443?
- [ ] hooks/prepull-images/README.md:The images to be pulled can be passed as arguments.  (TODO: Add example)
- [ ] hack/BUILD.bazel:# TODO: this does not work: we need to tell the task about the sources
- [ ] hack/BUILD.bazel:# TODO: this does not work: we need to tell the task about the sources
- [ ] hack/machine_types/README.md:TODO:
- [ ] hack/verify-staticcheck.sh:  # TODO: Add verification for these directories.
- [ ] Makefile:# TODO: just invoke tools/get_workspace_status.sh?

/help
